apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello.fullname" . }}-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Hello world!</title>
    <style>
    html { color-scheme: light dark; }
    body { width: 35em; margin: 0 auto;
    font-family: Tahoma, Verdana, Arial, sans-serif; }
    </style>
    </head>
    <body>
    <h1>Hello {{ .Values.hello }}!</h1>
    </body>
    </html>
