name: Helm Charts

on:
  push:
    branches:
      - main
      - releases/**
  pull_request:
  workflow_dispatch:

env:
  is_main_branch: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}
  is_release_branch: ${{ github.ref_type == 'branch' && startsWith(github.ref_name, 'releases/') }}
  target_branch: ${{ github.ref_type == 'pull_request' && github.event.pull_request.base.ref || github.ref_name }}

jobs:
  lint-charts:
    name: Lint Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Add helm repositories
        run: ./bin/add-repos

      - name: List changed
        id: list-changed
        run: |
          changed=$(ct list-changed --config etc/ct.yaml --target-branch ${{ env.target_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Lint charts
        if: ${{ steps.list-changed.outputs.changed == 'true' }}
        run: ct lint --config etc/ct.yaml --target-branch ${{ env.target_branch }}

  test-charts:
    name: Test Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Add helm repositories
        run: ./bin/add-repos

      - name: List changed
        id: list-changed
        run: |
          changed=$(ct list-changed --config etc/ct.yaml --target-branch ${{ env.target_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create kind cluster
        if: ${{ steps.list-changed.outputs.changed == 'true' }}
        uses: helm/kind-action@v1.4.0

      - name: Test charts
        if: ${{ steps.list-changed.outputs.changed == 'true' }}
        run: ct install --config etc/ct.yaml --target-branch ${{ env.target_branch }}

  release-charts:
    name: Release Charts
    if: ${{ env.is_main_branch == 'true' || env.is_release_branch == 'true' }}
    needs:
      - lint-charts
      - test-charts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set git user
        uses: git-actions/set-user@v1

      - name: Install Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add helm repositories
        run: ./bin/add-repos

      - name: Run chart releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          config: etc/cr.yaml
          mark_as_latest: ${{ env.is_main_branch == 'true' }}
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
