name: Release Please PR

on:
  push:
    branches:
      - release-please-**

jobs:

  revert-renovate-comments:
    name: Revert Renovate Comments
    # This is a work-around to release please removing comments with it's yaml parser.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Revert Renovate Comments
        run: |
          git diff -U0 HEAD~1 HEAD > /tmp/release-please.patch
          sed -i '/#\\s?renovate: /d' /tmp/release-please.patch
          message="$(git log --format=%B -n 1 HEAD)"
          git reset --hard HEAD~1
          git apply /tmp/release-please.patch --unidiff-zero
          git add .
          git commit -m "${message}"
          git push --force
