name: Renovate

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  workflow_run:
    workflows:
      - pages-build-deployment
    types:
      - completed

jobs:

  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@5c6c06aa0e3d7a6a9b6cba05c078c51631b5f11a # v39.1.1
        with:
          configurationFile: etc/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
