name: Renovate

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  workflow_run:
    workflows:
      - pages-build-deployment
    types:
      - completed

jobs:

  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@89bd050bafa5a15de5d9383e3129edf210422004 # v40.1.5
        with:
          configurationFile: etc/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
