name: Renovate

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  workflow_run:
    workflows:
      - pages-build-deployment
    types:
      - completed

jobs:

  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@c134f38c01867794a23c35e86660bd9609caf30c # v40.1.4
        with:
          configurationFile: etc/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
