name: Renovate

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:

  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Run Renovate
        uses: renovatebot/github-action@v36.0.4
        with:
          configurationFile: etc/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
