name: Renovate

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  workflow_run:
    workflows:
      - pages-build-deployment
    types:
      - completed

jobs:

  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@b266b24b144602ed4f512f0773009d026722f4cc # v40.2.6
        with:
          configurationFile: etc/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
